var qbBidSysSayc = `# Q-plus Bridge bidding system file

.version = 15.7
.description.eng = "Standard American Yellow Card (Q-plus)"
.description.deu = "Standard-American Yellow Card (Q-plus)"
.description.fra = "Standard Américain Yellow Card (Q-plus)"
.description.ita = "Standard Americano Yellow Card (Q-plus)"
.description.dan = "Standard American Yellow Card (Q-plus)"
.description.pol = "Standard American Yellow Card (Q-plus)"

Conventions
Y B-strong-artificial.bid-2C.forcing-until-3MA
Y B-1MA-5-cards.all-seats
Y B-1MI-prefer.minor-general
Y B-1NT.v-1.min-hcp.p15
Y B-1NT.v-1.max-hcp.p17
Y B-1NT.nv-1.min-hcp.p15
Y B-1NT.nv-1.max-hcp.p17
Y B-1NT.v-2.min-hcp.p15
Y B-1NT.v-2.max-hcp.p17
Y B-1NT.nv-2.min-hcp.p15
Y B-1NT.nv-2.max-hcp.p17
Y B-1NT.v-3.min-hcp.p15
Y B-1NT.v-3.max-hcp.p17
Y B-1NT.nv-3.min-hcp.p15
Y B-1NT.nv-3.max-hcp.p17
Y B-1NT.v-4.min-hcp.p15
Y B-1NT.v-4.max-hcp.p17
Y B-1NT.nv-4.min-hcp.p15
Y B-1NT.nv-4.max-hcp.p17
Y B-1NT-style.weak-5-heart
Y B-1NT-style.weak-5-spade
Y B-1NT-style.allow-5-4-half-stop
Y B-2D.weak.all-seats
Y B-2MA.weak.all-seats
Y B-2NT.strong-balanced.range-20-21
Y B-3NT.strong-balanced
Y B-4NT.solid-minor
Y B-5MI.preemptive
Y A-1MI-double-jump.preemptive
Y A-1MI-Truscott-2NT
Y A-1MI-2MA.unpassed-nodouble.is-strong
Y A-1MI-2MA.unpassed-double.is-fit
Y A-1MI-2MA.passed-nodouble.is-fit
Y A-1MI-2MA.passed-double.is-fit
Y A-1C-2D.unpassed-nodouble.is-strong
Y A-1C-2D.unpassed-double.is-fit
Y A-1C-2D.passed-nodouble.is-fit
Y A-1C-2D.passed-double.is-fit
Y A-1D-3C.unpassed-nodouble.is-strong
Y A-1D-3C.unpassed-double.is-fit
Y A-1D-3C.passed-nodouble.is-fit
Y A-1D-3C.passed-double.is-fit
Y A-1C-prefer-major
Y A-1C-1NT.range-7-10
Y A-1C-2NT.range-13-15
Y A-1C-passed-2NT.range-11-12
Y A-1D-2NT.range-13-15
Y A-1D-passed-2NT.range-11-12
Y A-1MA-1NT-min-support.points-6
Y A-1MA-2NT.support-4-strong
Y A-1MA-Truscott-2NT
Y A-1MA-splinter
Y A-1MA-passed-2NT.support-4
Y A-1MA-3MI.unpassed-nodouble.is-strong
Y A-1MA-3MI.unpassed-double.is-fit
Y A-1MA-3MI.passed-nodouble.is-fit
Y A-1MA-3MI.passed-double.is-fit
Y A-1H-2S.unpassed-nodouble.is-strong
Y A-1H-2S.unpassed-double.is-fit
Y A-1H-2S.passed-nodouble.is-fit
Y A-1H-2S.passed-double.is-fit
Y A-1S-3H.unpassed-nodouble.is-strong
Y A-1S-3H.unpassed-double.is-fit
Y A-1S-3H.passed-nodouble.is-fit
Y A-1S-3H.passed-double.is-fit
Y A-jump-shift-to-3.is-very-strong
Y A-2-over-1-min.hcp-10
Y A-1NT-Stayman
Y A-1NT-2C-major-4-4.answer-2H
Y A-1NT-5-major-always
Y A-1NT-Jacoby-transfer.always
Y A-1NT-Jacoby-minor.spades-for-minors
Y A-1NT-Jacoby-plus.Smolen
Y A-1NT-Jacoby-plus.direct-3MA-shows-6
Y A-1NT-3-minor.is-inviting
Y A-1NT-2C-x-3-minor.is-forcing
Y A-1NT-transfer-level-4.Texas
Y A-artificial-2C.negative-2D
Y A-use-second-negative
Y A-3NT-transfer
Y A-2NT.Stayman
Y A-2NT-transfer-level-3.below-1
Y A-2NT-transfer-level-3.spades-for-minors
Y A-2NT-transfer-level-4.Texas
Y A-2NT-3C-major-4-4.answer-3H
Y A-2MA-3MI.unpassed-nodouble.is-strong
Y A-2MA-3MI.unpassed-double.is-weak
Y A-2MA-3MI.passed-nodouble.is-weak
Y A-2MA-3MI.passed-double.is-weak
Y A-2H-2S.unpassed-nodouble.is-strong
Y A-2H-2S.unpassed-double.is-weak
Y A-2H-2S.passed-nodouble.is-weak
Y A-2H-2S.passed-double.is-weak
Y A-2S-3H.unpassed-nodouble.is-strong
Y A-2S-3H.unpassed-double.is-weak
Y A-2S-3H.passed-nodouble.is-weak
Y A-2S-3H.passed-double.is-weak
Y A-2MA-2NT.feature-showing
Y R-1-1-1NT.hcp-range-3
Y R-1H-1S-1NT.as-with-diamonds
Y G-new-minor-forcing
Y R-1-1-2NT.range-18-19
Y R-1H-1S-2NT.range-18-19
Y R-1MA-2-2NT.weak
Y G-2NT-new-minor-forcing
Y R-1-1-three-card-raise-possible
Y R-splinter-above-reverse
Y G-fourth-suit-forcing
Y G-trial-bid.long-suit
Y G-weak-reraise
Y G-trial-bid-to-3NT
Y O-Weak-Jump-Overcall.all-suits
Y O-Unusual-Notrump
Y O-Michaels
Y O-Leaping-Michaels
Y O-Jump-Cue-Bid
Y O-Jump-Cue-Bid-resp-dbl
Y O-1S-1NT-2S-X.is-penalty
Y O-1S-1NT-2S-p-p-X.is-take-out-general
Y O-1S-1NT-p-p-X.is-take-out-general
Y O-1H-1NT-2H-X.is-penalty
Y O-1H-1NT-2H-p-p-X.is-take-out-general
Y O-1H-1NT-p-p-X.is-take-out-general
Y O-1D-1NT-2D-X.is-penalty
Y O-1D-1NT-2D-p-p-X.is-take-out-general
Y O-1C-1NT-2C-X.is-penalty
Y O-1C-1NT-2C-p-p-X.is-take-out-general
Y O-1MI-1NT-2MI-2MA.is-one-suiter
Y O-1MI-1NT-2MI-p-p-2MA.is-one-suiter
Y O-1NT-x-pos2.is-penalty
Y O-1NT-x-notpassed-is-pos2
Y C-Sputnik.until-2S
Y C-1C-1D-dbl.shows-majors
Y C-1MI-1H-dbl.shows-spades
Y C-weak-jump.after-overcall
Y C-cue-double-is-strong
Y C-responsive-double
Y C-competitive-double
Y C-unassuming-cue-bids
Y C-1NT-doubled.all-escape
Y S-Cue-Bids.are-used
Y S-Gerber.classic
Y S-Blackwood.classic
Y S-Malowan

`;
